// Generated by CoffeeScript 1.8.0

/*
pickupSounds.coffee

plays a random sound file
when the space bar is pressed
 */
var init, update;

document.title = 'Pickup Sounds';

env.SOUND_PATH = '../sounds/';

env.USE_AUDIO_TAG = true;

env.ENGINE_BOTTOM_PANEL = 'Press the space bar to hear a random sound';

init = function() {
  return Greenhorn.start();
};

update = function() {
  if (keysDown[KEYS.SPACE]) {
    return new Sound({
      url: "jalastram/SFX_Pickup_" + (Math.round(Math.random() * 50)) + ".wav",
      playOnLoad: true
    });
  }
};
