// Generated by CoffeeScript 1.8.0

/*
startup.coffee

The absolute minimum that needs to
be done in order to create a Greenhorn page
 */
var init, update;

document.title = 'Startup Page';

init = function() {
  return Greenhorn.start();
};

update = function() {};
