// Generated by CoffeeScript 1.8.0

/*
textBoxTimer.coffee

a demonstration of two classes at once
 */

(function() {
  var display, timer;

  document.title = 'Timer Demo';

  env.ENGINE.rightHeader = 'CONTROLS';

  timer = null;

  display = null;

  this.init = function() {
    Greenhorn.start();
    timer = new Timer(false);
    display = new TextBox({
      fontSize: 60,
      borderVisible: false,
      text: (timer.getElapsedTime() / 1000).toFixed(2)
    });
    Greenhorn.addButton({
      label: 'START',
      onclick: function() {
        return timer.start();
      }
    });
    Greenhorn.addButton({
      label: 'PAUSE',
      onclick: function() {
        return timer.pause();
      }
    });
    Greenhorn.addButton({
      label: 'RESTART',
      onclick: function() {
        return timer.restart();
      }
    });
    return Greenhorn.addButton({
      label: 'STOP',
      onclick: function() {
        return timer.stop();
      }
    });
  };

  this.update = function() {
    return display.set('text', (timer.getElapsedTime() / 1000).toFixed(2));
  };

}).call(this);
