// Generated by CoffeeScript 1.8.0

/*
timerDemon.coffee
Written by Seth Bullock
sedabull@gmail.com
 */

(function() {
  var display, timer;

  document.title = 'Timer Demo';

  env.ENGINE.rightHeader = 'BUTTONS';

  env.ENGINE.leftHeader = 'INFORMATION';

  timer = null;

  display = null;

  this.init = function() {
    Greenhorn.start();
    timer = new Timer(false);
    display = new TextBox({
      fontSize: 60,
      borderVisible: false,
      text: (timer.getElapsedTime() / 1000).toFixed(2)
    });
    Greenhorn.addButton({
      label: 'START',
      onclick: function() {
        return timer.start();
      }
    });
    Greenhorn.addButton({
      label: 'PAUSE',
      onclick: function() {
        return timer.pause();
      }
    });
    Greenhorn.addButton({
      label: 'RESTART',
      onclick: function() {
        return timer.restart();
      }
    });
    Greenhorn.addButton({
      label: 'STOP',
      onclick: function() {
        return timer.stop();
      }
    });
    return $('#gh-left-panel').append('<h4 class=\'gh-sub-h\'>Instructions</h4>\n<p class=\'gh-p\'>\nUse the buttons on the right-hand side to experiment\nwith the four primary timer functions: play, pause,\nrestart, and stop. The elapsed time is displayed\non the canvas using a Greenhorn TextBox.\n</p>\n<h4 class=\'gh-sub-h\'>Discussion</h4>\n<p class=\'gh-p\'>\nThe timer class is used internally by the Greenhorn AniSprite\nto determine when to change frames. It could also be used to\noffset particular events, measure and compare a player\'s performance\nto others, or set a time limit on a particular game.\n</p>');
  };

  this.update = function() {
    return display.set('text', (timer.getElapsedTime() / 1000).toFixed(2));
  };

}).call(this);
