// Generated by CoffeeScript 1.8.0

/*
environment.coffee

The Greenhorn Gaming environment object
 */

(function() {
  var game;

  game = typeof exports !== "undefined" && exports !== null ? exports : this;

  game.env = {
    FRAME_RATE: 25,
    BODY_BACKGROUND_COLOR: "goldenrod",
    ENGINE_TITLE: document.title,
    ENGINE_LEFT_PANEL: "LEFT PANEL",
    ENGINE_RIGHT_PANEL: "RIGHT PANEL",
    ENGINE_BOTTOM_PANEL: "BOTTOM PANEL",
    ENGINE_CANVAS_COLOR: "black",
    ENGINE_BACKGROUND_COLOR: "darkgreen",
    ENGINE_CANVAS_ERROR: "your web browser does not support the <canvas> tag",
    IMAGE_PATH: "",
    SPRITE_DEFAULT_CONFIG: {
      x: 0,
      y: 0,
      z: 0,
      a: 0,
      dx: 0,
      dy: 0,
      dz: 0,
      da: 0,
      ddx: 0,
      ddy: 0,
      ddz: 0,
      dda: 0,
      width: 64,
      height: 64,
      imageFile: "",
      visible: true,
      boundAction: "WRAP"
    },
    TEXTBOX_DEFAULT_CONFIG: {
      z: -1,
      text: "*-TextBox-*",
      align: "center",
      backgroundColor: "black",
      backgroundAlpha: 1.0,
      backgroundVisible: true,
      borderSize: 5,
      borderColor: "white",
      borderAlpha: 1.0,
      borderVisible: true,
      fontName: "Arial",
      fontSize: 8,
      fontColor: "white",
      fontAlpha: 1.0,
      marginsTop: 5,
      marginsBottom: 5,
      marginsRight: 5,
      marginsLeft: 5
    },
    SOUND_PATH: "",
    SOUND_DEFAULT_URL: "",
    TIMER_START_ON_CONSTRUCTION: true,
    BUTTON_DEFAULT_LABEL: "Launch the Missiles!"
  };

}).call(this);
